### PR TITLE
Next 0.0.5

### PR DESCRIPTION
**Pull request by AndyObtiva**
Hi, I added support for bookmarks, which I really wanted for my own personal use.

Also, the app now starts instantly by fetching radio stations from the web API gradually in the background to avoid making the user wait for the app to start while fetching 10,000 radio stations from the Internet.

Last but not least, I refactored the entire project structure to be more object-oriented and follow the MVC pattern with `Model` and `View` module namespaces containing models and views.

I was wondering, since you added me to the authors of the project, could you please also send me an invitation to become a Gem author too on RubyGems? You just have to visit the Ownership page of the `rubio-radio` gem and invite my email "andy.am@gmail.com" under Add Owner: https://rubygems.org/gems/rubio-radio/owners

I hope it's not too much to ask. That way, I could deploy updates directly and avoid wasting your time (of course, you may still deploy further updates yourself and correct things you don't like to make more releases if needed).

You may learn more about the 0.0.5 changes in the change log below.

Cheers!

---

# Change Log

## 0.0.5

- Upgrade to glimmer-dsl-libui v0.5.20
- Add/Remove currently playing radio station to bookmarks (remembered across app restarts by storing station UUID in a YAML file locally)
- View menu with "All", "Bookmarks", and "Playing" View menu items
- Command option `--[no-]bookmarks` to show/hide bookmarks in table
- Command option `--[no-]gradual` to load radio stations gradually (preventing user from waiting for app to start) or avoid loading gradually

mac all with bookmarks

mac bookmarks

### CODE REVIEW

**Comment by kojix2** [comment]
Hi Andy

I was surprised to see so many changes included.
I just read the pull request twice.

I didn't fully understand the code, but I understand there are three changes.

1. Refactoring
2. Bookmarking
3. Getting stations little by little

The DSLs `enabled` and `checked` seems to use comparison operators. I think you mean directional and bidirectional data-binding. It is a bit difficult here.

I sent an email to the Ruby Gem owner inviting you to join.

I considered giving you the right to commit to the repository. However, I thought it would be better not to do so. Because if I did, I might give up the effort to read and understand each and every one of your code.

Your work always surprises me.
Thanks for the pull request.

**Comment by AndyObtiva** [comment]
Yeah, sorry about the big changes. I had to make the refactoring to facilitate future work with much more maintainable code.

> I didn't fully understand the code, but I understand there are three changes.
> 
> Refactoring
> Bookmarking
> Getting stations little by little

Your understanding is correct.

> The DSLs enabled and checked seems to use comparison operators. I think you mean directional and bidirectional data-binding. It is a bit difficult here.

Also, the arrows are part of the [Glimmer DSL for data-binding](https://github.com/AndyObtiva/glimmer-dsl-libui#data-binding) (`<=` means unidirecitonal data-binding and `<=>` means bidirectional data-binding). If you stop thinking of them in the basic Ruby way and instead think of them declaratively as arrows that represent the flow of data between the view property and the model attribute, it gets much much simpler to think about them. They are simple declarations of which sides receive data when the other side is updated, which cut down the amount of repetitive code I have to write by 10x at least. Maybe it gets confusing when the model is declared as also the view by using `self`. This can be improved upon by using a presenter model, which I did not do. I treated the view as its own model, which is not the best way of using data-binding, so I apologize. I'll try to improve in a future refactoring.

You can learn more about data-binding here (and feel free to ask me questions about it anytime, on [the Glimmer Gitter chat](https://gitter.im/AndyObtiva/glimmer) if you want):
https://github.com/AndyObtiva/glimmer-dsl-libui#data-binding

> I sent you an email inviting you to become a RubyGem owner.
> 
> I considered giving you the right to commit to the repository. However, I thought it would be better not to do so. Because if I did, I might give up the effort to read and understand your code.

I accepted your RubyGems invitation just to be a backup pusher of the gem, but I won't push gems in the future except in emergencies (like if you become unavailable and a big bug is discovered by someone). 

I will continue to submit pull requests for you to review and learn the code.

The code might be surprising only if you are not used to data-binding yet. Once you get used to it, the code should not be that surprising. I used bidirectional data-binding a lot in Java desktop development at work in the past, but it was not declarative like in Ruby, so I had to write pages and pages of code just to do data-binding. It is much simpler in Glimmer. In any case, bidirectional data-binding originated in Microsoft technologies I think like C# Windows Forms and WPF.

Anyways, if you want to do homework on it, you can read more about data-binding uses in Glimmer DSL for LibUI, and then document them in Wikipedia. Right now, the [Wikipedia data binding](https://en.wikipedia.org/wiki/Data_binding) page does not have Ruby. Glimmer is one of the first frameworks to support data binding in Ruby, but it has no page on Wikipedia. You could do your homework and then document your learning by creating a Glimmer page in Wikipedia with a very brief summary (I cannot create it as the author because that is considered biased) and then link to it from the [Wikipedia data binding](https://en.wikipedia.org/wiki/Data_binding) and [Wikipedia UI data binding](https://en.wikipedia.org/wiki/UI_data_binding) pages. This is optional. If you don't have time or don't want to, it's absolutely OK of course. But, I'd appreciate it if you do it.

**Comment by AndyObtiva** [comment]
In any case, thank you for merging.

**Comment by AndyObtiva** [comment]
By the way, you are welcome to release 0.0.5 if you think it’s ready. I’ll only push gems in case of emergencies. I’ll leave it to you to do in general.

**Comment by kojix2** [comment]
I have just released 0.0.5.

Data-binding looks like a great idea that I'm simply not familiar with. (I was thinking of `TkVariable` in Ruby/Tk)

 `=>`, `<=`, and `<=>` can have various meanings. [In the Ruby language `=>` would be right assignment operator](https://bugs.ruby-lang.org/issues/15921), and in Ruby 3.1 this already works. Although glimmer-dsl-libui does not use `=>`, I felt this needed some attention.

```ruby
(1 + 2) => a
p a

# Ruby 3.1 | 3
# Ruby 3.0 | nil
# Ruby 2.7 | syntax error, unexpected =>, expecting end-of-input (SyntaxError)
```

I believe you are developing and shaping new ideas that have not been used much or existed in the Ruby GUI world. (I don't know if this is something worth describing on Wikipedia, but if it becomes widely used, yes, it will, eventually.)

**Comment by AndyObtiva** [comment]
I'm glad for releasing 0.0.5

Actually, there is no need for `=>` in data-binding, yet only `<=>` and `<=`.

You either want bidirectional data-binding where the view updates the model and the model updates the view like in read/write controls that can produce data like `entry` and `spinner`, or you want unidirecitonal data-binding where the model updates the view only like in read-only controls like `label` or read-only properties like `enabled`. 

I do not know of any cases where there is a need to have the view update the model without the model updating the view back in general. But, if that ever becomes needed for some weird reason, you can use `<=>` and then add `on_read: ->(value) {control.property}` converter to prevent the property value of the view from changing.

**Comment by AndyObtiva** [comment]
> I believe you are developing and shaping new ideas that have not been used much or existed in the Ruby GUI world. (I don't know if this is something worth describing on Wikipedia, but if it becomes widely used, yes, it will, eventually.)

It is definitely worth describing on Wikipedia since there are other descriptions for C# and Java as you can see in the data binding and UI data binding pages on Wikipedia. And, the Ruby version is clearly much shorter and more succinct than the C# and Java versions, thus superior, so it would be educational to people to let them know what is possible in Ruby. I don't think being widely used is an important criterion in deciding whether to document on Wikipedia or not. The Glimmer data-binding features have been around since 2007 (they used to be less advanced though), so it is long overdue for Glimmer to have a Wikipedia page. I just couldn't create it myself for being the author of the library, so I would greatly appreciate it if you ever have the chance, time, and will to do it.

**Comment by rubyFeedback** [comment]
Hmm. Does the "updating in the background" work? When I tried it on windows I had like 15 stations or so but no further change. The stations that were shown worked fine via vlc though.

**Comment by kojix2** [comment]
@rubyFeedback 
Use `--page-count` option to check if the radio station is still loading in the background.
If the number of pages does not increase, it may not be loading properly.
We have not fully tested the Windows environment, so it is possible that you see some bugs.

**Comment by AndyObtiva** [comment]
@rubyFeedback Please include a screenshot of how the app looks like on Windows for you. I want to see if the `>` button is showing / active or if is hidden / disabled.

**Comment by AndyObtiva** [comment]
@rubyFeedback Let's continue further communication over here (please submit a screenshot for your app on Windows as soon as possible over there): 
https://github.com/kojix2/rubio-radio/issues/10

**Pull request merged**
