### PR TITLE
Window and table customizations

### PR DESCRIPTION
**Pull request by AndyObtiva**
Hi,

I added command options to allow hiding the top menu bar and customizing the displayed number of rows per page, adjusting the window height accordingly. This resulted in a much smaller app window size on Linux.

Small Screen Example:

```
rubio --per-page 6 --no-menu
```

small screen example

Using `--per-page` will automatically calculate/adjust the window height, but you can also manually override the window width and height with `--width` and `--height` in case the calculation is inaccurate for your platform settings. However, the window width can only be enlarged, but not shrunk unfortunately (it seems libui auto-calculates the minimum width and does not allow going below it).

I added a few new features to `refined_table` in the latest [glimmer-dsl-libui](https://github.com/AndyObtiva/glimmer-dsl-libui) like disabling pagination buttons when not applicable or needed, and showing page count. It looks good on Mac, but not Linux, so I kept it disabled by default (optional).

Page Count Example:

```
rubio --page-count
```

small screen example

Here are all the new changes:

- Command option `--per-page` for number of rows per page to display
- Command option `--page-count` for displaying page count ("of PAGE_COUNT pages")
- Command option `--width` for initial window width
- Command option `--height` for initial window height
- Command option `--no-menu` to remove the top menu bar and save screen space when not needed (on Mac it is always on because the menu bar does not take application screen space)
- Help menu About menu item to display message box with application license
- If `--per-page` is specified and `--height` is not specified, attempt to calculate intial window height for each platform automatically based on number of rows per page

Please make a v0.0.4 release if you think the changes are good enough for now.

Cheers!

### CODE REVIEW

**Comment by kojix2** [comment]
Thank you very much. It was very helpful. 
So this is how you use the DSL for Glimmer::LibUI::Application

* `options` `option`
* `before_body do ... end` `body do ... end` 
* `.launch` `.launched_application`

I learned a lot.
I thought the error process was gone, but it was restored at the end.

I will release v0.0.5. However, I am still not satisfied with the width of the buttons on Ubuntu. When I have time, I will look at the libui-ng unix code and see if there is a way to make the buttons smaller. They appear to be implemented using basic GTK widgets.

**Comment by kojix2** [comment]
I added your name to authors in gemspec, is that ok? If you don't like it, I'll remove it before releasing.

**Comment by kojix2** [comment]
I have added your name to gemspec authors since you provided so much code, but if you do not need it, please let me know and I will remove it.

**Comment by AndyObtiva** [comment]
You’re welcome. 

I don’t mind having my name in the gem authors. Thanks. 

And, I'm glad you learned the use of `Glimmer::LibUI::Application` (alias for `Glimmer::LibUI::CustomWindow`). It is a new mixin in Glimmer DSL for LibUI that facilitates building applications (custom windows). It automates/simplifies passing in `options` and building/showing the `body` using the `launch` class method. It supports `before_body` (executes before building the body, useful for setting up instance variables and attributes) and `after_body` (executes after building the body, useful for setting up timers or observers that depend on the view). In any case, `Glimmer::LibUI::Application` extends `Glimmer::LibUI::CustomControl`, which enables building class-based custom controls (a.k.a. reusable components with new keywords not originally in libui like `refined_table`) as explained in the Custom Keywords Glimmer DSL for LibUI README section: https://github.com/AndyObtiva/glimmer-dsl-libui#custom-keywords

About the buttons being too wide, I believe that is a bug in c libui. The buttons are inside a horizontal box that should have just conformed to the specified width of the window and auto scaled the buttons to fit within it (e.g. if window width is 250 pixels and we have 5 buttons in a horizontal box, they should be about 50 pixels in width each). Maybe, you can report the issue to [libui-ng](https://github.com/libui-ng/libui-ng) and ask them to make an official release. They’ve added a lot of features, but haven’t made an official release, which is frustrating. Their process is not very lean as such as it risks releasing too many things at once instead of dividing the risk down to smaller releases. It would be better if they released often (even if we have access to their packages from their build system). If you can convince them to make a release, then you and I can do new work on supporting it in Ruby LibUI and Glimmer DSL for LibUI.

**Comment by AndyObtiva** [comment]
By the way, I I kept the upcoming version number to 0.0.4 (instead of 0.0.5) because you didn't release 0.0.4 yet, so that should be the next version to release if I am not mistaken.

**Pull request merged**
